# Generated by Django 2.1.1 on 2018-09-05 04:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 9, 5, 4, 38, 35, 565784, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
