# Generated by Django 2.1.1 on 2018-09-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
